# Generated by Django 5.1.1 on 2024-12-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_product_rename_created_on_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
